### ISSUE TITLE
Create a generic chatbot interface able to be inherited

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chatbot#10]
# Introduction
All chatbots have common tasks and status that allows them to have generic functions while at the same time having their own specific “personality”. To achieve so, we need to create a `Chatbot` interface able to provide a structure for future chatbots, as to ensure they all a similar pattern when possible.

# Task Description
- [ ] Declare the interface `ChatBot`, which provides the general interface a bot needs to overload as to be able to be instantiated. This interface should include the following methods and types and/or a similar structure for instantiating bots on a long term basis (method definition can be changed):
  - [ ] `init() => void`: Initial behaviour for the bot to use whenever it starts.
  - [ ] `type ChatBotStatus: enum`: An enum describing all the possible status the bot can have.
  - [ ] `type ChatBotCommands: enum`: An enum describing all the methods the bot can have.
  - [ ] `type ChatBotMessages: enum`: An enum describing all the possible messages the bot can have.
  - [ ] `state: { [key: ChatStatus]: ChatStatus }`: An object containing an array describing the possible states the bot can go from/to.
  - [ ] `directory: { [key: HOPRAddress]: number }`: An object mapping interacting users and their messages.length
  - [ ] `winners[]: HOPRAddress[]`: An array showcasing the participants that have successfully completed the bounty from the bot.
  - [ ] `commands: { [key: ChatBotCommand]: () => void }`: An array describing which commands are enabled
  - [ ] `send(address: HOPRAddress, message: HOPRMessage)`: A method for sending message to a node
  - [ ] `stateReducer(address: HOPRAddress, from: ChatStatus, to: ChatStatus)`: A method that is being called whenever the bot changes state for a given HOPRNode, and updates the sate as needed for that user.
  - [ ] `onMessage() => void`: A method that is being called back when the bot receives a message
  - [ ] `onSend() => void`: A method that is called back when the bot sends a message
