### ISSUE TITLE
Create an reusable library able to connect to the Twitter API

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chatbot#11]
# Introduction

All bots will require to read data from the Twitter API to verify some actions. Of course, these actions depend on the bot, but in most cases, we'll need to ensure the `hoprnet` is mentioned, as well as specific tags. We need a generic interface that can be extended by the bots in a generic fashion.

# Task Description
- [ ] Create an interface that can be implemented by any both that contains the following methods:
  - [ ] `parseTweet(url: TweekLink) => { user_mentions, hashtags, content }`: Method able to obtain the relevant data from a given week.
  - [ ] `onTweet(callback: ChatPromise(res:ChatBotSuccess => ChatMessage, rej:ChatBotFailure => ChatMessage) => ())`: Method able to be hooked to a generic `ChatPromise` which resolves to a specific `ChatMessage` given a condition within the chatbot.
