### ISSUE TITLE
Create an extendable interface that connects to the LinkDrop SDK and manages the payments of the bounties

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-chatbot#12]
# Introduction

We need to ensure that the bots are able to pay back bounties given specific rules are completed. To do so, we'll be using the [LinkDrop SDK](https://www.npmjs.com/package/@linkdrop/sdk) to manage the creation of the payment based on the run-time parameters, by creating an interface each bot can extend. Each bot will be able to provide links with ERC-20 or Ether in them, and whenever they are deployed, initialize the adequate contract calls as to budget their rewards.

# Task Description
- [ ] Provide an interface `IPayable` which adds the following methods and objects to the bot:
  - [ ] `setupSDK()`: Method able to read from `ENV` to initialize the LinkDrop SDK and fail if it misses a param.
  - [ ] `setupProxy(key: EthereumPrivateKey, campaignId: "$BOT_NAME", budget: number )`: Method able to deploy a proxy contract with a given budget to be used for generating the rewards.
  - [ ] `rules: { "rewardees": number, "reward": number }`: The rules of engagement for the bot to know how many bounties it can pay per person.
  - [ ] `payBounty(address: HOPRAddress)`: Method to pay the bounty which generates a LinkDrop link and sends it to the HOPR Address.

# Notes
It's important to be able to provide network and other parameters for the LinkDrop SDK. Make sure to add these as environment variables.
