### ISSUE TITLE
Modify chatbot to allow interactive actions on a daily basis

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-chatbot#54]
# Introduction

We'll be looking to ask people to do activities through chatbot as part of the dailies.

# Task Description
- [ ] Modify chatbot so it can run on `daily` mode
  - [ ] `daily $day` shows the timeframe where the bot can listen to you, whether the daily is completed and the time left.
  - [ ] `daily $day view` shows a list of actions, (e.g. open a payment channel to me) and whether `message.from` completed it.
  - [ ] `daily $day verify $action` prompts the bot to execute an action that verifies the user completes everything.
  - [ ] `daily $day url` returns the URL where that daily results can be seen by anyone.
